acmeair-customerservice:
  environment:
    - JAVA_OPTS=-Dspring.profiles.active=jpa,perf -Dserver.port=8080 -Dcse.service.registry.address=http://sc.servicecomb.io:30100

acmeair-bookingservice:
  environment:
    - JAVA_OPTS=-Dspring.profiles.active=mongodb,perf -Dserver.port=8080 -Dspring.data.mongodb.host=mongo.acmeair.com -Dcse.service.registry.address=http://sc.servicecomb.io:30100
